# ---------------------------- PARTE DE USUARIOS ----------------------------
# mostrar todos los usuarios
GET http://localhost:8080/sistReserva/usuarios

# mostrar usuario por ID
GET http://localhost:8080/sistReserva/usuarios/31

# mostrar reservas de usuario
GET http://localhost:8080/sistReserva/usuarios/20/reservas

# mostrar reservas pendientes
GET http://localhost:8080/sistReserva/usuarios/reservas-pendientes

# usuarios agregados dentro de un rango de fechas
GET http://localhost:8080/sistReserva/usuarios/reservas/rango-fechas?fechaInicio=2023-12-30&fechaFin=2024-01-31

# guardar
POST http://localhost:8080/sistReserva/usuarios/guardar
Content-Type: application/json

{
  "fechaRegistro": "2024-02-01",
  "nombre": "R",
  "apellidoPaterno": "S",
  "apellidoMaterno": "J",
  "correo": ""
}

# actualizar
PUT http://localhost:8080/sistReserva/usuarios/actualizar/31
Content-Type: application/json

{
  "nombre": "R",
  "apellidoPaterno": "S",
  "apellidoMaterno": "J",
  "correo": "",
  "telefono": ""
}

# Borrar
DELETE http://localhost:8080/sistReserva/usuarios/eliminar/31

# ---------------------------- PARTE DE SERVICIOS ----------------------------
# mostrar todos los servicios
GET http://localhost:8080/sistReserva/servicios

# mostrar servicio por id
GET http://localhost:8080/sistReserva/servicios/37

# mostrar servicios por categoria
GET http://localhost:8080/sistReserva/servicios/categoria/Streaming

# mostrar segun el campo disponible {DISPONIBLE, RESERVADO, MANTENIMIENTO, NO_DISPONIBLE}
GET http://localhost:8080/sistReserva/servicios/disponibles/MANTENIMIENTO

# mostrar segun su ubicacion
GET http://localhost:8080/sistReserva/servicios/ubicacion/Tijuana

# mostrar segun su duracion
GET http://localhost:8080/sistReserva/servicios/duracion/0.000000003S

# guardar un servicio
POST http://localhost:8080/sistReserva/servicios/guardar
Content-Type: application/json

{
  "nombre": "Spotify",
  "precio": 110.00,
  "categoria": "Streaming",
  "duracion": 150,
  "disponible": "NO_DISPONIBLE",
  "ubicacion": "CDMX",
  "descripcion": "Escuchar musica sin anuncios"
}

# actualizar
PUT http://localhost:8080/sistReserva/servicios/actualizar/47
Content-Type: application/json

{
  "nombre": "Spotify",
  "precio": 150.00,
  "categoria": "Streaming",
  "duracion": 250,
  "disponible": "RESERVADO",
  "ubicacion": "CDMX",
  "descripcion": "Escuchar musica sin anuncios y sin conexion a internet"
}

# Borrar
DELETE http://localhost:8080/sistReserva/servicios/eliminar/47
